packages:
  - "astrhythm"
  - "astravestis"

allowBuilds:
  esbuild: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
  vitest: 4.1.11
  "@vitest/browser-playwright": 4.1.11
  "@vitest/coverage-v8": 4.1.11

overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
